//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Ribbon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ribbon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Ribbon", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string G_BaoCao {
            get {
                return ResourceManager.GetString("G_BaoCao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager level.
        /// </summary>
        internal static string G_CapDuyet {
            get {
                return ResourceManager.GetString("G_CapDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string G_DangKy {
            get {
                return ResourceManager.GetString("G_DangKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization.
        /// </summary>
        internal static string G_HRM {
            get {
                return ResourceManager.GetString("G_HRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        internal static string G_Luong {
            get {
                return ResourceManager.GetString("G_Luong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval.
        /// </summary>
        internal static string G_PheDuyet {
            get {
                return ResourceManager.GetString("G_PheDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string G_TaiKhoan {
            get {
                return ResourceManager.GetString("G_TaiKhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build level.
        /// </summary>
        internal static string I_CapDuyet {
            get {
                return ResourceManager.GetString("I_CapDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days-off (hours).
        /// </summary>
        internal static string I_DKBu {
            get {
                return ResourceManager.GetString("I_DKBu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        internal static string I_DKPhep {
            get {
                return ResourceManager.GetString("I_DKPhep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PW.
        /// </summary>
        internal static string I_DoiMK {
            get {
                return ResourceManager.GetString("I_DoiMK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HRM.
        /// </summary>
        internal static string I_HRM {
            get {
                return ResourceManager.GetString("I_HRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remain leave.
        /// </summary>
        internal static string I_Phepton {
            get {
                return ResourceManager.GetString("I_Phepton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay-slip.
        /// </summary>
        internal static string I_PhieuLuong {
            get {
                return ResourceManager.GetString("I_PhieuLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIT Finalization.
        /// </summary>
        internal static string I_QTT_TNCN {
            get {
                return ResourceManager.GetString("I_QTT_TNCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string T_NV {
            get {
                return ResourceManager.GetString("T_NV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string T_QL {
            get {
                return ResourceManager.GetString("T_QL", resourceCulture);
            }
        }
    }
}
