//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AF_HRNew {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AF_HRNew() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AF_HRNew", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your reason for rejecting.
        /// </summary>
        internal static string errorText {
            get {
                return ResourceManager.GetString("errorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to excel.
        /// </summary>
        internal static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        internal static string gv_Code {
            get {
                return ResourceManager.GetString("gv_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total days.
        /// </summary>
        internal static string gv_Days {
            get {
                return ResourceManager.GetString("gv_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string gv_Dep {
            get {
                return ResourceManager.GetString("gv_Dep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date.
        /// </summary>
        internal static string gv_Fromdate {
            get {
                return ResourceManager.GetString("gv_Fromdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From time.
        /// </summary>
        internal static string gv_Fromtime {
            get {
                return ResourceManager.GetString("gv_Fromtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string gv_Fullname {
            get {
                return ResourceManager.GetString("gv_Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total hours.
        /// </summary>
        internal static string gv_Hours {
            get {
                return ResourceManager.GetString("gv_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason to leave.
        /// </summary>
        internal static string gv_LeaveReason {
            get {
                return ResourceManager.GetString("gv_LeaveReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave type.
        /// </summary>
        internal static string gv_Leavetype {
            get {
                return ResourceManager.GetString("gv_Leavetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pertime.
        /// </summary>
        internal static string gv_Pertime {
            get {
                return ResourceManager.GetString("gv_Pertime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string gv_Pos {
            get {
                return ResourceManager.GetString("gv_Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason to reject.
        /// </summary>
        internal static string gv_Reason {
            get {
                return ResourceManager.GetString("gv_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary type name.
        /// </summary>
        internal static string gv_SalaryType {
            get {
                return ResourceManager.GetString("gv_SalaryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date.
        /// </summary>
        internal static string gv_Todate {
            get {
                return ResourceManager.GetString("gv_Todate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To time.
        /// </summary>
        internal static string gv_Totime {
            get {
                return ResourceManager.GetString("gv_Totime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string reason {
            get {
                return ResourceManager.GetString("reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        internal static string sync {
            get {
                return ResourceManager.GetString("sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t sync.
        /// </summary>
        internal static string unsync {
            get {
                return ResourceManager.GetString("unsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        internal static string w {
            get {
                return ResourceManager.GetString("w", resourceCulture);
            }
        }
    }
}
