//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class K_Feedback {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal K_Feedback() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.K_Feedback", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send feedback.
        /// </summary>
        internal static string hSendmessage {
            get {
                return ResourceManager.GetString("hSendmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   First page  .
        /// </summary>
        internal static string lbFirstPage {
            get {
                return ResourceManager.GetString("lbFirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Last page  .
        /// </summary>
        internal static string lbLastPage {
            get {
                return ResourceManager.GetString("lbLastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content:.
        /// </summary>
        internal static string lbmessage {
            get {
                return ResourceManager.GetString("lbmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Next  .
        /// </summary>
        internal static string lbNextPage {
            get {
                return ResourceManager.GetString("lbNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Previous  .
        /// </summary>
        internal static string lbPreviousPage {
            get {
                return ResourceManager.GetString("lbPreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Feedback.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Employee Feedbacks.
        /// </summary>
        internal static string title_2 {
            get {
                return ResourceManager.GetString("title_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input infomation for feedback!.
        /// </summary>
        internal static string vMessage {
            get {
                return ResourceManager.GetString("vMessage", resourceCulture);
            }
        }
    }
}
