//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class K_ViewEmpKPI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal K_ViewEmpKPI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.K_ViewEmpKPI", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not exists assessment period in here!.
        /// </summary>
        internal static string alert {
            get {
                return ResourceManager.GetString("alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected any rows on the grid..
        /// </summary>
        internal static string alertSelectNull {
            get {
                return ResourceManager.GetString("alertSelectNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string btEdit {
            get {
                return ResourceManager.GetString("btEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve all.
        /// </summary>
        internal static string btn_Approval {
            get {
                return ResourceManager.GetString("btn_Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competencies point.
        /// </summary>
        internal static string colCompetencyRating {
            get {
                return ResourceManager.GetString("colCompetencyRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string colDepartment {
            get {
                return ResourceManager.GetString("colDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        internal static string colDivision {
            get {
                return ResourceManager.GetString("colDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        internal static string colEmpID {
            get {
                return ResourceManager.GetString("colEmpID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comp - Kpi Factor.
        /// </summary>
        internal static string colFactor {
            get {
                return ResourceManager.GetString("colFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string colID {
            get {
                return ResourceManager.GetString("colID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job factor.
        /// </summary>
        internal static string colJob_Factor {
            get {
                return ResourceManager.GetString("colJob_Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPI Point.
        /// </summary>
        internal static string colKPIRating {
            get {
                return ResourceManager.GetString("colKPIRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPI factor.
        /// </summary>
        internal static string colKPI_Factor {
            get {
                return ResourceManager.GetString("colKPI_Factor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working location.
        /// </summary>
        internal static string colLocation {
            get {
                return ResourceManager.GetString("colLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA&apos;s Period.
        /// </summary>
        internal static string colPeriodName {
            get {
                return ResourceManager.GetString("colPeriodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating total.
        /// </summary>
        internal static string colRating_Total {
            get {
                return ResourceManager.GetString("colRating_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string colReject {
            get {
                return ResourceManager.GetString("colReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string colSection {
            get {
                return ResourceManager.GetString("colSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        internal static string colStartDate {
            get {
                return ResourceManager.GetString("colStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Excel.
        /// </summary>
        internal static string ExportExcel {
            get {
                return ResourceManager.GetString("ExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string FillterByDep {
            get {
                return ResourceManager.GetString("FillterByDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working location.
        /// </summary>
        internal static string FillterByLocation {
            get {
                return ResourceManager.GetString("FillterByLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager levels.
        /// </summary>
        internal static string FillterByManager {
            get {
                return ResourceManager.GetString("FillterByManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group employees direct manager.
        /// </summary>
        internal static string GroupDirect {
            get {
                return ResourceManager.GetString("GroupDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group employees Level 3.
        /// </summary>
        internal static string GroupLevel3 {
            get {
                return ResourceManager.GetString("GroupLevel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assesment Period.
        /// </summary>
        internal static string lbPeriod {
            get {
                return ResourceManager.GetString("lbPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string lbYearID {
            get {
                return ResourceManager.GetString("lbYearID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        internal static string p {
            get {
                return ResourceManager.GetString("p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only manager can use this function!.
        /// </summary>
        internal static string PAalert {
            get {
                return ResourceManager.GetString("PAalert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string pa_Check {
            get {
                return ResourceManager.GetString("pa_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View data.
        /// </summary>
        internal static string ShowGrid {
            get {
                return ResourceManager.GetString("ShowGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review &amp; Approval Performance Assessment.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Report.
        /// </summary>
        internal static string ViewChart {
            get {
                return ResourceManager.GetString("ViewChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage Report.
        /// </summary>
        internal static string ViewChart2 {
            get {
                return ResourceManager.GetString("ViewChart2", resourceCulture);
            }
        }
    }
}
