//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KPI_Summary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KPI_Summary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.KPI_Summary", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public data was failed..
        /// </summary>
        internal static string alertFail {
            get {
                return ResourceManager.GetString("alertFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance assessment data was published..
        /// </summary>
        internal static string alertSuscess {
            get {
                return ResourceManager.GetString("alertSuscess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string colDepartment {
            get {
                return ResourceManager.GetString("colDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        internal static string colDivision {
            get {
                return ResourceManager.GetString("colDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string colManager {
            get {
                return ResourceManager.GetString("colManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string colSection {
            get {
                return ResourceManager.GetString("colSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string gvDetail_colA {
            get {
                return ResourceManager.GetString("gvDetail_colA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string gvDetail_colB {
            get {
                return ResourceManager.GetString("gvDetail_colB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string gvDetail_colC {
            get {
                return ResourceManager.GetString("gvDetail_colC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string gvDetail_colD {
            get {
                return ResourceManager.GetString("gvDetail_colD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string gvDetail_colE {
            get {
                return ResourceManager.GetString("gvDetail_colE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incentive.
        /// </summary>
        internal static string gvDetail_colF {
            get {
                return ResourceManager.GetString("gvDetail_colF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        internal static string gvDetail_colG {
            get {
                return ResourceManager.GetString("gvDetail_colG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string gvDetail_colH {
            get {
                return ResourceManager.GetString("gvDetail_colH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string gvDetail_colI {
            get {
                return ResourceManager.GetString("gvDetail_colI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        internal static string gvDetail_colJ {
            get {
                return ResourceManager.GetString("gvDetail_colJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string gvDetail_colK {
            get {
                return ResourceManager.GetString("gvDetail_colK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maternity
        ///Leave/unpaid leave days.
        /// </summary>
        internal static string gvDetail_colL {
            get {
                return ResourceManager.GetString("gvDetail_colL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual WD.
        /// </summary>
        internal static string gvDetail_colM {
            get {
                return ResourceManager.GetString("gvDetail_colM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Basic Gross Salary.
        /// </summary>
        internal static string gvDetail_colN {
            get {
                return ResourceManager.GetString("gvDetail_colN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Salary 6months ZPV.
        /// </summary>
        internal static string gvDetail_colO {
            get {
                return ResourceManager.GetString("gvDetail_colO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA.
        /// </summary>
        internal static string gvDetail_colP {
            get {
                return ResourceManager.GetString("gvDetail_colP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string gvDetail_colQ {
            get {
                return ResourceManager.GetString("gvDetail_colQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string lbDelete {
            get {
                return ResourceManager.GetString("lbDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string lbEndtime {
            get {
                return ResourceManager.GetString("lbEndtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        internal static string lbPublic {
            get {
                return ResourceManager.GetString("lbPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reassessment.
        /// </summary>
        internal static string lbReassessment {
            get {
                return ResourceManager.GetString("lbReassessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string lbSave {
            get {
                return ResourceManager.GetString("lbSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string lbStarttime {
            get {
                return ResourceManager.GetString("lbStarttime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View data.
        /// </summary>
        internal static string ShowGrid {
            get {
                return ResourceManager.GetString("ShowGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics of group.
        /// </summary>
        internal static string Tab_1 {
            get {
                return ResourceManager.GetString("Tab_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail report.
        /// </summary>
        internal static string Tab_2 {
            get {
                return ResourceManager.GetString("Tab_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUMMARY PERFORMANCE ASSESSMENT.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
    }
}
