//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RC_DepManager {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RC_DepManager() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RC_DepManager", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string colCheckerID {
            get {
                return ResourceManager.GetString("colCheckerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string colCheckerName {
            get {
                return ResourceManager.GetString("colCheckerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string colDep {
            get {
                return ResourceManager.GetString("colDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General director.
        /// </summary>
        internal static string colGeneralDirector {
            get {
                return ResourceManager.GetString("colGeneralDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department manager.
        /// </summary>
        internal static string colGroupL2 {
            get {
                return ResourceManager.GetString("colGroupL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string colGroupL3_1 {
            get {
                return ResourceManager.GetString("colGroupL3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General HR.
        /// </summary>
        internal static string colHRManager {
            get {
                return ResourceManager.GetString("colHRManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        internal static string colLine {
            get {
                return ResourceManager.GetString("colLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department head.
        /// </summary>
        internal static string colManager {
            get {
                return ResourceManager.GetString("colManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string colManagerID {
            get {
                return ResourceManager.GetString("colManagerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string colManagerName {
            get {
                return ResourceManager.GetString("colManagerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll group.
        /// </summary>
        internal static string colSec {
            get {
                return ResourceManager.GetString("colSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string colStatus {
            get {
                return ResourceManager.GetString("colStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable list.
        /// </summary>
        internal static string optInUse {
            get {
                return ResourceManager.GetString("optInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible list.
        /// </summary>
        internal static string optNotUse {
            get {
                return ResourceManager.GetString("optNotUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEPARTMENT-MANAGER.
        /// </summary>
        internal static string tieude {
            get {
                return ResourceManager.GetString("tieude", resourceCulture);
            }
        }
    }
}
