//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RC_Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RC_Menu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RC_Menu", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer to update.
        /// </summary>
        internal static string btnTransfer {
            get {
                return ResourceManager.GetString("btnTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruit.
        /// </summary>
        internal static string G_Recruit {
            get {
                return ResourceManager.GetString("G_Recruit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build level.
        /// </summary>
        internal static string I_CapDuyet {
            get {
                return ResourceManager.GetString("I_CapDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department-Manager.
        /// </summary>
        internal static string I_DepManagerRC {
            get {
                return ResourceManager.GetString("I_DepManagerRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager - Employee.
        /// </summary>
        internal static string I_LineManagerRC {
            get {
                return ResourceManager.GetString("I_LineManagerRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval.
        /// </summary>
        internal static string I_RCApproval {
            get {
                return ResourceManager.GetString("I_RCApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnel requisition.
        /// </summary>
        internal static string I_RCRegist {
            get {
                return ResourceManager.GetString("I_RCRegist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion &amp; Adjustment.
        /// </summary>
        internal static string I_RCRegist_2 {
            get {
                return ResourceManager.GetString("I_RCRegist_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistic Report.
        /// </summary>
        internal static string I_RCStatistic {
            get {
                return ResourceManager.GetString("I_RCStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History view.
        /// </summary>
        internal static string I_RCView {
            get {
                return ResourceManager.GetString("I_RCView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View request.
        /// </summary>
        internal static string I_RCViewList {
            get {
                return ResourceManager.GetString("I_RCViewList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Recruitment.
        /// </summary>
        internal static string I_ReportRC {
            get {
                return ResourceManager.GetString("I_ReportRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize.
        /// </summary>
        internal static string I_Sync {
            get {
                return ResourceManager.GetString("I_Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register by group.
        /// </summary>
        internal static string optGroup {
            get {
                return ResourceManager.GetString("optGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual register.
        /// </summary>
        internal static string optMyself {
            get {
                return ResourceManager.GetString("optMyself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager groups.
        /// </summary>
        internal static string tabRCDep_Manager {
            get {
                return ResourceManager.GetString("tabRCDep_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other users.
        /// </summary>
        internal static string tabRCHR_Manager {
            get {
                return ResourceManager.GetString("tabRCHR_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager levels.
        /// </summary>
        internal static string tabRCLevel {
            get {
                return ResourceManager.GetString("tabRCLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit manager.
        /// </summary>
        internal static string tabRCLevel_Edit {
            get {
                return ResourceManager.GetString("tabRCLevel_Edit", resourceCulture);
            }
        }
    }
}
