//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RC_Registration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RC_Registration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RC_Registration", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emp.ID [] is not exists. Please retype!.
        /// </summary>
        internal static string AlertNull {
            get {
                return ResourceManager.GetString("AlertNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee [] has resigned. Please retype!.
        /// </summary>
        internal static string AlertResign {
            get {
                return ResourceManager.GetString("AlertResign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register succeed..
        /// </summary>
        internal static string AlertSuccess {
            get {
                return ResourceManager.GetString("AlertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save success.
        /// </summary>
        internal static string AlertSuccessTmp {
            get {
                return ResourceManager.GetString("AlertSuccessTmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string btnTinhGio {
            get {
                return ResourceManager.GetString("btnTinhGio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string c {
            get {
                return ResourceManager.GetString("c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 days / 30 ngày.
        /// </summary>
        internal static string chk_30 {
            get {
                return ResourceManager.GetString("chk_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60 days / 60 ngày.
        /// </summary>
        internal static string chk_60 {
            get {
                return ResourceManager.GetString("chk_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None / Không.
        /// </summary>
        internal static string chk_None {
            get {
                return ResourceManager.GetString("chk_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete?.
        /// </summary>
        internal static string confirmDelete {
            get {
                return ResourceManager.GetString("confirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string gv_A {
            get {
                return ResourceManager.GetString("gv_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Date.
        /// </summary>
        internal static string gv_ApprovingDate_L1 {
            get {
                return ResourceManager.GetString("gv_ApprovingDate_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Date.
        /// </summary>
        internal static string gv_ApprovingDate_L2 {
            get {
                return ResourceManager.GetString("gv_ApprovingDate_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Date.
        /// </summary>
        internal static string gv_ApprovingDate_L3 {
            get {
                return ResourceManager.GetString("gv_ApprovingDate_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string gv_ApprovingReason_L1 {
            get {
                return ResourceManager.GetString("gv_ApprovingReason_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string gv_ApprovingReason_L2 {
            get {
                return ResourceManager.GetString("gv_ApprovingReason_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string gv_ApprovingReason_L3 {
            get {
                return ResourceManager.GetString("gv_ApprovingReason_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Status L1.
        /// </summary>
        internal static string gv_ApprovingStatus_L1 {
            get {
                return ResourceManager.GetString("gv_ApprovingStatus_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Status L2.
        /// </summary>
        internal static string gv_ApprovingStatus_L2 {
            get {
                return ResourceManager.GetString("gv_ApprovingStatus_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Status L3.
        /// </summary>
        internal static string gv_ApprovingStatus_L3 {
            get {
                return ResourceManager.GetString("gv_ApprovingStatus_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string gv_C {
            get {
                return ResourceManager.GetString("gv_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string gv_Delete {
            get {
                return ResourceManager.GetString("gv_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeID.
        /// </summary>
        internal static string gv_EmployeeID {
            get {
                return ResourceManager.GetString("gv_EmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string gv_EmployeeName {
            get {
                return ResourceManager.GetString("gv_EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Date.
        /// </summary>
        internal static string gv_FinalDate {
            get {
                return ResourceManager.GetString("gv_FinalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Status.
        /// </summary>
        internal static string gv_FinalStatus {
            get {
                return ResourceManager.GetString("gv_FinalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Time.
        /// </summary>
        internal static string gv_FromTime {
            get {
                return ResourceManager.GetString("gv_FromTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Date.
        /// </summary>
        internal static string gv_HRCheckingDate {
            get {
                return ResourceManager.GetString("gv_HRCheckingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string gv_HRCheckingReason {
            get {
                return ResourceManager.GetString("gv_HRCheckingReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR Approval Status.
        /// </summary>
        internal static string gv_HRCheckingStatus {
            get {
                return ResourceManager.GetString("gv_HRCheckingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string gv_LeaveReason {
            get {
                return ResourceManager.GetString("gv_LeaveReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Type.
        /// </summary>
        internal static string gv_LeaveType {
            get {
                return ResourceManager.GetString("gv_LeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager L1.
        /// </summary>
        internal static string gv_ManagerName_L1 {
            get {
                return ResourceManager.GetString("gv_ManagerName_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager L2.
        /// </summary>
        internal static string gv_ManagerName_L2 {
            get {
                return ResourceManager.GetString("gv_ManagerName_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager L3.
        /// </summary>
        internal static string gv_ManagerName_L3 {
            get {
                return ResourceManager.GetString("gv_ManagerName_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerTime Name.
        /// </summary>
        internal static string gv_PerTimeName {
            get {
                return ResourceManager.GetString("gv_PerTimeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reg Date.
        /// </summary>
        internal static string gv_RegDate {
            get {
                return ResourceManager.GetString("gv_RegDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        internal static string gv_StartDate {
            get {
                return ResourceManager.GetString("gv_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        internal static string gv_ToDate {
            get {
                return ResourceManager.GetString("gv_ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days off.
        /// </summary>
        internal static string gv_TotalDays {
            get {
                return ResourceManager.GetString("gv_TotalDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours off.
        /// </summary>
        internal static string gv_TotalHours {
            get {
                return ResourceManager.GetString("gv_TotalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Time.
        /// </summary>
        internal static string gv_ToTime {
            get {
                return ResourceManager.GetString("gv_ToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        internal static string gv_W {
            get {
                return ResourceManager.GetString("gv_W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name / Họ tên nhân viên:.
        /// </summary>
        internal static string lb1_1 {
            get {
                return ResourceManager.GetString("lb1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department/ Phòng ban:.
        /// </summary>
        internal static string lb1_2 {
            get {
                return ResourceManager.GetString("lb1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title / Chức vụ:.
        /// </summary>
        internal static string lb1_3 {
            get {
                return ResourceManager.GetString("lb1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division / Bộ phận:.
        /// </summary>
        internal static string lb1_4 {
            get {
                return ResourceManager.GetString("lb1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report to / Báo cáo đến:.
        /// </summary>
        internal static string lb1_5 {
            get {
                return ResourceManager.GetString("lb1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working location/ Địa điểm làm việc:.
        /// </summary>
        internal static string lb1_6 {
            get {
                return ResourceManager.GetString("lb1_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender/ Giới tính:.
        /// </summary>
        internal static string lb1_7 {
            get {
                return ResourceManager.GetString("lb1_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Payroll Group / Nhóm:.
        /// </summary>
        internal static string lb1_8 {
            get {
                return ResourceManager.GetString("lb1_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZPV/ SANG/ PHYTO/ METRO HEALTH Staff / Nhân viên ZPV/ SANG/ PHYTO/ METRO HEALTH.
        /// </summary>
        internal static string lb2_1 {
            get {
                return ResourceManager.GetString("lb2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casual Staff / Nhân viên không thường xuyên.
        /// </summary>
        internal static string lb2_2 {
            get {
                return ResourceManager.GetString("lb2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full time / Nhân viên toàn thời gian.
        /// </summary>
        internal static string lb2_3 {
            get {
                return ResourceManager.GetString("lb2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade from casual staff / Chuyển từ nhân viên không thường xuyên sang ZPV/ SANG/ PHYTO/ METRO HEALTH.
        /// </summary>
        internal static string lb2_4 {
            get {
                return ResourceManager.GetString("lb2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full time / Nhân viên toàn thời gian.
        /// </summary>
        internal static string lb2_5 {
            get {
                return ResourceManager.GetString("lb2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasonal / Nhân viên thời vụ.
        /// </summary>
        internal static string lb2_6 {
            get {
                return ResourceManager.GetString("lb2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maternity replacement / Nhân viên thay thế thai sản.
        /// </summary>
        internal static string lb2_7 {
            get {
                return ResourceManager.GetString("lb2_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New headcount &lt;br&gt;
        ///Vị trí mới.
        /// </summary>
        internal static string lb2_8 {
            get {
                return ResourceManager.GetString("lb2_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacement &lt;br&gt;
        ///Vị trí thay thế.
        /// </summary>
        internal static string lb2_9 {
            get {
                return ResourceManager.GetString("lb2_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting date / Ngày bắt đầu làm việc:.
        /// </summary>
        internal static string lb4_1 {
            get {
                return ResourceManager.GetString("lb4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casual contract duration / Thời hạn hợp đồng cho nhân viên không thường xuyên:.
        /// </summary>
        internal static string lb4_2 {
            get {
                return ResourceManager.GetString("lb4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Probation / Trong thời gian thử việc.
        /// </summary>
        internal static string lb5_1 {
            get {
                return ResourceManager.GetString("lb5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After Probation / Sau thời gian thử việc.
        /// </summary>
        internal static string lb5_2 {
            get {
                return ResourceManager.GetString("lb5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Gross Salary / Lương Gộp hàng tháng.
        /// </summary>
        internal static string lb5_3 {
            get {
                return ResourceManager.GetString("lb5_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Gross Transport support and field support fee / Hỗ trợ xăng xe &amp; công tác phí Gộp hàng tháng.
        /// </summary>
        internal static string lb5_4 {
            get {
                return ResourceManager.GetString("lb5_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Gross other support fee / Hỗ trợ Gộp khác hàng tháng.
        /// </summary>
        internal static string lb5_5 {
            get {
                return ResourceManager.GetString("lb5_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach application form / Đính kèm bản dự tuyển.
        /// </summary>
        internal static string lbAttach_AF {
            get {
                return ResourceManager.GetString("lbAttach_AF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach CE’s approval / Đính kèm phê duyệt của TGD.
        /// </summary>
        internal static string lbAttach_CE {
            get {
                return ResourceManager.GetString("lbAttach_CE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach JD / Đính kèm bản mô tả công việc.
        /// </summary>
        internal static string lbAttach_JD {
            get {
                return ResourceManager.GetString("lbAttach_JD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee / Nhân viên:.
        /// </summary>
        internal static string lbEmpID_Replace {
            get {
                return ResourceManager.GetString("lbEmpID_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string lbl_Alert {
            get {
                return ResourceManager.GetString("lbl_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee information / Thông tin nhân sự:.
        /// </summary>
        internal static string lbPart_1 {
            get {
                return ResourceManager.GetString("lbPart_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position information / Thông tin vị trí:.
        /// </summary>
        internal static string lbPart_2 {
            get {
                return ResourceManager.GetString("lbPart_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the person replaced / Tên nhân viên được thay thế:.
        /// </summary>
        internal static string lbPart_3 {
            get {
                return ResourceManager.GetString("lbPart_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probation period / Thời hạn thử việc:.
        /// </summary>
        internal static string lbPart_4 {
            get {
                return ResourceManager.GetString("lbPart_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefit information / Thông tin về phúc lợi:.
        /// </summary>
        internal static string lbPart_5 {
            get {
                return ResourceManager.GetString("lbPart_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark / Lưu ý.
        /// </summary>
        internal static string lbRemarks {
            get {
                return ResourceManager.GetString("lbRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string lbtDangKy {
            get {
                return ResourceManager.GetString("lbtDangKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string lbtSaveTemp {
            get {
                return ResourceManager.GetString("lbtSaveTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Update .
        /// </summary>
        internal static string lbtSua {
            get {
                return ResourceManager.GetString("lbtSua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cancel .
        /// </summary>
        internal static string lbtThoat {
            get {
                return ResourceManager.GetString("lbtThoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working....
        /// </summary>
        internal static string opt3_1 {
            get {
                return ResourceManager.GetString("opt3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resigned.
        /// </summary>
        internal static string opt3_2 {
            get {
                return ResourceManager.GetString("opt3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In budget / Trong ngân sách.
        /// </summary>
        internal static string optButget_1 {
            get {
                return ResourceManager.GetString("optButget_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not in budget / Ngoài ngân sách.
        /// </summary>
        internal static string optButget_2 {
            get {
                return ResourceManager.GetString("optButget_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female / Nữ.
        /// </summary>
        internal static string opt_Female {
            get {
                return ResourceManager.GetString("opt_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZPV.
        /// </summary>
        internal static string opt_G1 {
            get {
                return ResourceManager.GetString("opt_G1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZPS.
        /// </summary>
        internal static string opt_G2 {
            get {
                return ResourceManager.GetString("opt_G2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SANG.
        /// </summary>
        internal static string opt_G3 {
            get {
                return ResourceManager.GetString("opt_G3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHYTO.
        /// </summary>
        internal static string opt_G4 {
            get {
                return ResourceManager.GetString("opt_G4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string opt_G5 {
            get {
                return ResourceManager.GetString("opt_G5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to METRO HEALTH.
        /// </summary>
        internal static string opt_G6 {
            get {
                return ResourceManager.GetString("opt_G6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASUAL.
        /// </summary>
        internal static string opt_G7 {
            get {
                return ResourceManager.GetString("opt_G7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male / Nam.
        /// </summary>
        internal static string opt_Male {
            get {
                return ResourceManager.GetString("opt_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left date.
        /// </summary>
        internal static string textLeftDate {
            get {
                return ResourceManager.GetString("textLeftDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave from.
        /// </summary>
        internal static string textMaternityDate {
            get {
                return ResourceManager.GetString("textMaternityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        internal static string textSalary {
            get {
                return ResourceManager.GetString("textSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERSONNEL REQUISITION FORM.
        /// </summary>
        internal static string tieude {
            get {
                return ResourceManager.GetString("tieude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROMOTION &amp; ADJUSTMENT FORM.
        /// </summary>
        internal static string tieude_2 {
            get {
                return ResourceManager.GetString("tieude_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [EDIT]  PERSONNEL REQUISITION FORM.
        /// </summary>
        internal static string tieude_edit {
            get {
                return ResourceManager.GetString("tieude_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please attach CE’s approval for new headcount.
        /// </summary>
        internal static string vAttach_CE {
            get {
                return ResourceManager.GetString("vAttach_CE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please attach JD for new headcount.
        /// </summary>
        internal static string vAttach_JD {
            get {
                return ResourceManager.GetString("vAttach_JD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter butget type.
        /// </summary>
        internal static string vButget {
            get {
                return ResourceManager.GetString("vButget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter division.
        /// </summary>
        internal static string vDepartment {
            get {
                return ResourceManager.GetString("vDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is exist on db..
        /// </summary>
        internal static string vDuplicate {
            get {
                return ResourceManager.GetString("vDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter employee.
        /// </summary>
        internal static string vEmployee {
            get {
                return ResourceManager.GetString("vEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter employee replace.
        /// </summary>
        internal static string vEmployee_Replace {
            get {
                return ResourceManager.GetString("vEmployee_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter gender.
        /// </summary>
        internal static string vGender {
            get {
                return ResourceManager.GetString("vGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter department.
        /// </summary>
        internal static string vLine {
            get {
                return ResourceManager.GetString("vLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter location.
        /// </summary>
        internal static string vLocation {
            get {
                return ResourceManager.GetString("vLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your leave reason.
        /// </summary>
        internal static string vLydo {
            get {
                return ResourceManager.GetString("vLydo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn điều kiện.
        /// </summary>
        internal static string vOptCondition {
            get {
                return ResourceManager.GetString("vOptCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter payroll group.
        /// </summary>
        internal static string vPayroll {
            get {
                return ResourceManager.GetString("vPayroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter name of other group.
        /// </summary>
        internal static string vPayroll_Other {
            get {
                return ResourceManager.GetString("vPayroll_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Position Information.
        /// </summary>
        internal static string vPosition {
            get {
                return ResourceManager.GetString("vPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose probation period.
        /// </summary>
        internal static string vPromotionType {
            get {
                return ResourceManager.GetString("vPromotionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose casual contract duration.
        /// </summary>
        internal static string vPromotionType_2 {
            get {
                return ResourceManager.GetString("vPromotionType_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter report to.
        /// </summary>
        internal static string vReportTo {
            get {
                return ResourceManager.GetString("vReportTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter effective date.
        /// </summary>
        internal static string vStartDate {
            get {
                return ResourceManager.GetString("vStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting date must be later than today.
        /// </summary>
        internal static string vStartDate_2 {
            get {
                return ResourceManager.GetString("vStartDate_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting date must be different the sunday..
        /// </summary>
        internal static string vStartDate_3 {
            get {
                return ResourceManager.GetString("vStartDate_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total hours must be greater than 0.
        /// </summary>
        internal static string vTongGio {
            get {
                return ResourceManager.GetString("vTongGio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total dayoff must be greater than zero.
        /// </summary>
        internal static string vTongNgay {
            get {
                return ResourceManager.GetString("vTongNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough leave remain to register.
        /// </summary>
        internal static string vTongNgay2 {
            get {
                return ResourceManager.GetString("vTongNgay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter From Date.
        /// </summary>
        internal static string vTuNgay {
            get {
                return ResourceManager.GetString("vTuNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [From Date] must be less than or equal [To Date].
        /// </summary>
        internal static string vValidDate {
            get {
                return ResourceManager.GetString("vValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        internal static string w {
            get {
                return ResourceManager.GetString("w", resourceCulture);
            }
        }
    }
}
