//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RC_ViewReport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RC_ViewReport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RC_ViewReport", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working place.
        /// </summary>
        internal static string band_Location {
            get {
                return ResourceManager.GetString("band_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report To.
        /// </summary>
        internal static string band_ReportTo {
            get {
                return ResourceManager.GetString("band_ReportTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to XLS.
        /// </summary>
        internal static string btnXlsExport {
            get {
                return ResourceManager.GetString("btnXlsExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to XLSX.
        /// </summary>
        internal static string btnXlsxExport {
            get {
                return ResourceManager.GetString("btnXlsxExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string col_A {
            get {
                return ResourceManager.GetString("col_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After adjustment.
        /// </summary>
        internal static string col_AfterChange {
            get {
                return ResourceManager.GetString("col_AfterChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string col_B {
            get {
                return ResourceManager.GetString("col_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before adjustment.
        /// </summary>
        internal static string col_BeforeChange {
            get {
                return ResourceManager.GetString("col_BeforeChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        internal static string col_C {
            get {
                return ResourceManager.GetString("col_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payroll Group.
        /// </summary>
        internal static string col_D {
            get {
                return ResourceManager.GetString("col_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type change.
        /// </summary>
        internal static string col_E {
            get {
                return ResourceManager.GetString("col_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emp.ID.
        /// </summary>
        internal static string col_EmpID {
            get {
                return ResourceManager.GetString("col_EmpID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string col_F {
            get {
                return ResourceManager.GetString("col_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Information.
        /// </summary>
        internal static string col_G {
            get {
                return ResourceManager.GetString("col_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On probation.
        /// </summary>
        internal static string col_Group1 {
            get {
                return ResourceManager.GetString("col_Group1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After probation.
        /// </summary>
        internal static string col_Group2 {
            get {
                return ResourceManager.GetString("col_Group2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the person replaced.
        /// </summary>
        internal static string col_H {
            get {
                return ResourceManager.GetString("col_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effected Date.
        /// </summary>
        internal static string col_I {
            get {
                return ResourceManager.GetString("col_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Date.
        /// </summary>
        internal static string col_I1 {
            get {
                return ResourceManager.GetString("col_I1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probation Period.
        /// </summary>
        internal static string col_J {
            get {
                return ResourceManager.GetString("col_J", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casual Contract Duration.
        /// </summary>
        internal static string col_K {
            get {
                return ResourceManager.GetString("col_K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Gross Salary.
        /// </summary>
        internal static string col_L {
            get {
                return ResourceManager.GetString("col_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Gross Transport support and 
        ///field support fee.
        /// </summary>
        internal static string col_N {
            get {
                return ResourceManager.GetString("col_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other change.
        /// </summary>
        internal static string col_Other {
            get {
                return ResourceManager.GetString("col_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Gross other support fee.
        /// </summary>
        internal static string col_P {
            get {
                return ResourceManager.GetString("col_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved by.
        /// </summary>
        internal static string col_R {
            get {
                return ResourceManager.GetString("col_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved date.
        /// </summary>
        internal static string col_S {
            get {
                return ResourceManager.GetString("col_S", resourceCulture);
            }
        }
    }
}
