//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AF_ApprovalNew {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AF_ApprovalNew() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AF_ApprovalNew", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval.
        /// </summary>
        internal static string approval {
            get {
                return ResourceManager.GetString("approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string cbb_approve {
            get {
                return ResourceManager.GetString("cbb_approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string cbb_unapprove {
            get {
                return ResourceManager.GetString("cbb_unapprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your reason to reject.
        /// </summary>
        internal static string errorText {
            get {
                return ResourceManager.GetString("errorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string grDetail_HRReason {
            get {
                return ResourceManager.GetString("grDetail_HRReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string gvDetail_ApprovalReason {
            get {
                return ResourceManager.GetString("gvDetail_ApprovalReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string gvDetail_ApprovalStatus {
            get {
                return ResourceManager.GetString("gvDetail_ApprovalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string gvDetail_Date {
            get {
                return ResourceManager.GetString("gvDetail_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR checking.
        /// </summary>
        internal static string gvDetail_HRchecking {
            get {
                return ResourceManager.GetString("gvDetail_HRchecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string gvDetail_HRDate {
            get {
                return ResourceManager.GetString("gvDetail_HRDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager level 1.
        /// </summary>
        internal static string gvDetail_ManagerNameL1 {
            get {
                return ResourceManager.GetString("gvDetail_ManagerNameL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager level 2.
        /// </summary>
        internal static string gvDetail_ManagerNameL2 {
            get {
                return ResourceManager.GetString("gvDetail_ManagerNameL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager level 3.
        /// </summary>
        internal static string gvDetail_ManagerNameL3 {
            get {
                return ResourceManager.GetString("gvDetail_ManagerNameL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string gvDetail_Reason {
            get {
                return ResourceManager.GetString("gvDetail_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval.
        /// </summary>
        internal static string gv_Approval {
            get {
                return ResourceManager.GetString("gv_Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days off.
        /// </summary>
        internal static string gv_Days {
            get {
                return ResourceManager.GetString("gv_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string gv_Dep {
            get {
                return ResourceManager.GetString("gv_Dep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmpID.
        /// </summary>
        internal static string gv_EmpID {
            get {
                return ResourceManager.GetString("gv_EmpID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date.
        /// </summary>
        internal static string gv_Fromdate {
            get {
                return ResourceManager.GetString("gv_Fromdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From time.
        /// </summary>
        internal static string gv_Fromtime {
            get {
                return ResourceManager.GetString("gv_Fromtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string gv_FullName {
            get {
                return ResourceManager.GetString("gv_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours off.
        /// </summary>
        internal static string gv_Hours {
            get {
                return ResourceManager.GetString("gv_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave type.
        /// </summary>
        internal static string gv_LeaveType {
            get {
                return ResourceManager.GetString("gv_LeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pertime.
        /// </summary>
        internal static string gv_PerTime {
            get {
                return ResourceManager.GetString("gv_PerTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string gv_Pos {
            get {
                return ResourceManager.GetString("gv_Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason to leave.
        /// </summary>
        internal static string gv_Reason {
            get {
                return ResourceManager.GetString("gv_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reg date.
        /// </summary>
        internal static string gv_Regdate {
            get {
                return ResourceManager.GetString("gv_Regdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date.
        /// </summary>
        internal static string gv_Todate {
            get {
                return ResourceManager.GetString("gv_Todate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To time.
        /// </summary>
        internal static string gv_Totime {
            get {
                return ResourceManager.GetString("gv_Totime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval.
        /// </summary>
        internal static string pop_Caption {
            get {
                return ResourceManager.GetString("pop_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string reason {
            get {
                return ResourceManager.GetString("reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
    }
}
