//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AF_LeaveReport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AF_LeaveReport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AF_LeaveReport", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string col_A {
            get {
                return ResourceManager.GetString("col_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emp. ID.
        /// </summary>
        internal static string col_B {
            get {
                return ResourceManager.GetString("col_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string col_C {
            get {
                return ResourceManager.GetString("col_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting date.
        /// </summary>
        internal static string col_D {
            get {
                return ResourceManager.GetString("col_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        internal static string col_E {
            get {
                return ResourceManager.GetString("col_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string col_F {
            get {
                return ResourceManager.GetString("col_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string col_G {
            get {
                return ResourceManager.GetString("col_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining AL 2016.
        /// </summary>
        internal static string col_H {
            get {
                return ResourceManager.GetString("col_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AL 2017.
        /// </summary>
        internal static string col_I {
            get {
                return ResourceManager.GetString("col_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AL Used.
        /// </summary>
        internal static string col_J {
            get {
                return ResourceManager.GetString("col_J", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AL Remain.
        /// </summary>
        internal static string col_K {
            get {
                return ResourceManager.GetString("col_K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marriage/ Compassinate Leave.
        /// </summary>
        internal static string col_L {
            get {
                return ResourceManager.GetString("col_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sick Leave under 3 days/ year.
        /// </summary>
        internal static string col_M {
            get {
                return ResourceManager.GetString("col_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpaid Leave.
        /// </summary>
        internal static string col_N {
            get {
                return ResourceManager.GetString("col_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave for Examination.
        /// </summary>
        internal static string col_O {
            get {
                return ResourceManager.GetString("col_O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child’s Sick Leave.
        /// </summary>
        internal static string col_P {
            get {
                return ResourceManager.GetString("col_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sick Leave.
        /// </summary>
        internal static string col_Q {
            get {
                return ResourceManager.GetString("col_Q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diseases requiring long-term treatment.
        /// </summary>
        internal static string col_R {
            get {
                return ResourceManager.GetString("col_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregnancy Check-up.
        /// </summary>
        internal static string col_S {
            get {
                return ResourceManager.GetString("col_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maternity Leave.
        /// </summary>
        internal static string col_T {
            get {
                return ResourceManager.GetString("col_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscarriage, Abortion, Stillbirth.
        /// </summary>
        internal static string col_U {
            get {
                return ResourceManager.GetString("col_U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Having intrauterine devices or employees taking sterilization measures.
        /// </summary>
        internal static string col_V {
            get {
                return ResourceManager.GetString("col_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paternity Leave.
        /// </summary>
        internal static string col_W {
            get {
                return ResourceManager.GetString("col_W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health recovery after Sickness.
        /// </summary>
        internal static string col_X {
            get {
                return ResourceManager.GetString("col_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health recovery after Maternity leave.
        /// </summary>
        internal static string col_Y {
            get {
                return ResourceManager.GetString("col_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished calculate..
        /// </summary>
        internal static string lbMessage {
            get {
                return ResourceManager.GetString("lbMessage", resourceCulture);
            }
        }
    }
}
