//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class F_Registration3 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal F_Registration3() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.F_Registration3", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string c {
            get {
                return ResourceManager.GetString("c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete?.
        /// </summary>
        internal static string confirmDelete {
            get {
                return ResourceManager.GetString("confirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string gv_A {
            get {
                return ResourceManager.GetString("gv_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Date.
        /// </summary>
        internal static string gv_ApprovingDate_L1 {
            get {
                return ResourceManager.GetString("gv_ApprovingDate_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Date.
        /// </summary>
        internal static string gv_ApprovingDate_L2 {
            get {
                return ResourceManager.GetString("gv_ApprovingDate_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Date.
        /// </summary>
        internal static string gv_ApprovingDate_L3 {
            get {
                return ResourceManager.GetString("gv_ApprovingDate_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string gv_ApprovingReason_L1 {
            get {
                return ResourceManager.GetString("gv_ApprovingReason_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string gv_ApprovingReason_L2 {
            get {
                return ResourceManager.GetString("gv_ApprovingReason_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string gv_ApprovingReason_L3 {
            get {
                return ResourceManager.GetString("gv_ApprovingReason_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Status L1.
        /// </summary>
        internal static string gv_ApprovingStatus_L1 {
            get {
                return ResourceManager.GetString("gv_ApprovingStatus_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Status L2.
        /// </summary>
        internal static string gv_ApprovingStatus_L2 {
            get {
                return ResourceManager.GetString("gv_ApprovingStatus_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Status L3.
        /// </summary>
        internal static string gv_ApprovingStatus_L3 {
            get {
                return ResourceManager.GetString("gv_ApprovingStatus_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string gv_C {
            get {
                return ResourceManager.GetString("gv_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string gv_Delete {
            get {
                return ResourceManager.GetString("gv_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeID.
        /// </summary>
        internal static string gv_EmployeeID {
            get {
                return ResourceManager.GetString("gv_EmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string gv_EmployeeName {
            get {
                return ResourceManager.GetString("gv_EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Date.
        /// </summary>
        internal static string gv_FinalDate {
            get {
                return ResourceManager.GetString("gv_FinalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Status.
        /// </summary>
        internal static string gv_FinalStatus {
            get {
                return ResourceManager.GetString("gv_FinalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Date.
        /// </summary>
        internal static string gv_HRCheckingDate {
            get {
                return ResourceManager.GetString("gv_HRCheckingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string gv_HRCheckingReason {
            get {
                return ResourceManager.GetString("gv_HRCheckingReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR Approval Status.
        /// </summary>
        internal static string gv_HRCheckingStatus {
            get {
                return ResourceManager.GetString("gv_HRCheckingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string gv_LeaveReason {
            get {
                return ResourceManager.GetString("gv_LeaveReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Type.
        /// </summary>
        internal static string gv_LeaveType {
            get {
                return ResourceManager.GetString("gv_LeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager L1.
        /// </summary>
        internal static string gv_ManagerName_L1 {
            get {
                return ResourceManager.GetString("gv_ManagerName_L1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager L2.
        /// </summary>
        internal static string gv_ManagerName_L2 {
            get {
                return ResourceManager.GetString("gv_ManagerName_L2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager L3.
        /// </summary>
        internal static string gv_ManagerName_L3 {
            get {
                return ResourceManager.GetString("gv_ManagerName_L3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerTime Name.
        /// </summary>
        internal static string gv_PerTimeName {
            get {
                return ResourceManager.GetString("gv_PerTimeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reg Date.
        /// </summary>
        internal static string gv_RegDate {
            get {
                return ResourceManager.GetString("gv_RegDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        internal static string gv_StartDate {
            get {
                return ResourceManager.GetString("gv_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        internal static string gv_ToDate {
            get {
                return ResourceManager.GetString("gv_ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total days.
        /// </summary>
        internal static string gv_TotalDays {
            get {
                return ResourceManager.GetString("gv_TotalDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        internal static string gv_W {
            get {
                return ResourceManager.GetString("gv_W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerTime.
        /// </summary>
        internal static string lbCheDoNghi {
            get {
                return ResourceManager.GetString("lbCheDoNghi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        internal static string lbDenNgay {
            get {
                return ResourceManager.GetString("lbDenNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Type.
        /// </summary>
        internal static string lbLoaiNghi {
            get {
                return ResourceManager.GetString("lbLoaiNghi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string lbLyDoNghi {
            get {
                return ResourceManager.GetString("lbLyDoNghi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Day.
        /// </summary>
        internal static string lbNgayNghi {
            get {
                return ResourceManager.GetString("lbNgayNghi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensation leave.
        /// </summary>
        internal static string lbPhepbu {
            get {
                return ResourceManager.GetString("lbPhepbu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remain Leave.
        /// </summary>
        internal static string lbPhepTon {
            get {
                return ResourceManager.GetString("lbPhepTon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string lbtDangKy {
            get {
                return ResourceManager.GetString("lbtDangKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string lbtNhapLai {
            get {
                return ResourceManager.GetString("lbtNhapLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total days.
        /// </summary>
        internal static string lbTongNgay {
            get {
                return ResourceManager.GetString("lbTongNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        internal static string lbTuNgay {
            get {
                return ResourceManager.GetString("lbTuNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime registration.
        /// </summary>
        internal static string tieude {
            get {
                return ResourceManager.GetString("tieude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose pertime.
        /// </summary>
        internal static string ToolTipCheDoNghi {
            get {
                return ResourceManager.GetString("ToolTipCheDoNghi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose leave type.
        /// </summary>
        internal static string ToolTipLoaiNghi {
            get {
                return ResourceManager.GetString("ToolTipLoaiNghi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose leave date.
        /// </summary>
        internal static string ToolTipNgayNghi {
            get {
                return ResourceManager.GetString("ToolTipNgayNghi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter pertime.
        /// </summary>
        internal static string vCheDoNghi {
            get {
                return ResourceManager.GetString("vCheDoNghi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter To Date.
        /// </summary>
        internal static string vDenNgay {
            get {
                return ResourceManager.GetString("vDenNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter leave type.
        /// </summary>
        internal static string vLoaiNghi {
            get {
                return ResourceManager.GetString("vLoaiNghi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total dayoff must be greater than zero.
        /// </summary>
        internal static string vTongNgay {
            get {
                return ResourceManager.GetString("vTongNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough leave remain to register.
        /// </summary>
        internal static string vTongNgay2 {
            get {
                return ResourceManager.GetString("vTongNgay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter From Date.
        /// </summary>
        internal static string vTuNgay {
            get {
                return ResourceManager.GetString("vTuNgay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [From Date] must be less than or equal [To Date].
        /// </summary>
        internal static string vValidDate {
            get {
                return ResourceManager.GetString("vValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        internal static string w {
            get {
                return ResourceManager.GetString("w", resourceCulture);
            }
        }
    }
}
