//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Ribbon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ribbon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Ribbon", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Leave.
        /// </summary>
        internal static string G_Annual {
            get {
                return ResourceManager.GetString("G_Annual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string G_BaoCao {
            get {
                return ResourceManager.GetString("G_BaoCao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager level.
        /// </summary>
        internal static string G_CapDuyet {
            get {
                return ResourceManager.GetString("G_CapDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval.
        /// </summary>
        internal static string G_Checker {
            get {
                return ResourceManager.GetString("G_Checker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string G_DangKy {
            get {
                return ResourceManager.GetString("G_DangKy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string G_Employee {
            get {
                return ResourceManager.GetString("G_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization.
        /// </summary>
        internal static string G_HRM {
            get {
                return ResourceManager.GetString("G_HRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Assessment.
        /// </summary>
        internal static string G_KPI {
            get {
                return ResourceManager.GetString("G_KPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        internal static string G_Luong {
            get {
                return ResourceManager.GetString("G_Luong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string G_Manager {
            get {
                return ResourceManager.GetString("G_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager news.
        /// </summary>
        internal static string G_ManagerNews {
            get {
                return ResourceManager.GetString("G_ManagerNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create news.
        /// </summary>
        internal static string G_Marker {
            get {
                return ResourceManager.GetString("G_Marker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string G_News {
            get {
                return ResourceManager.GetString("G_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string G_Other {
            get {
                return ResourceManager.GetString("G_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval.
        /// </summary>
        internal static string G_PheDuyet {
            get {
                return ResourceManager.GetString("G_PheDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string G_TaiKhoan {
            get {
                return ResourceManager.GetString("G_TaiKhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string G_Viewer {
            get {
                return ResourceManager.GetString("G_Viewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build level.
        /// </summary>
        internal static string I_CapDuyet {
            get {
                return ResourceManager.GetString("I_CapDuyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval News.
        /// </summary>
        internal static string I_CheckNews {
            get {
                return ResourceManager.GetString("I_CheckNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Period.
        /// </summary>
        internal static string I_CreatePeriod {
            get {
                return ResourceManager.GetString("I_CreatePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days-off (hours).
        /// </summary>
        internal static string I_DKBu {
            get {
                return ResourceManager.GetString("I_DKBu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Registration.
        /// </summary>
        internal static string I_DKPhep {
            get {
                return ResourceManager.GetString("I_DKPhep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PW.
        /// </summary>
        internal static string I_DoiMK {
            get {
                return ResourceManager.GetString("I_DoiMK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Leave.
        /// </summary>
        internal static string I_DuyetPhep {
            get {
                return ResourceManager.GetString("I_DuyetPhep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HRM.
        /// </summary>
        internal static string I_HRM {
            get {
                return ResourceManager.GetString("I_HRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Assessment.
        /// </summary>
        internal static string I_KPI {
            get {
                return ResourceManager.GetString("I_KPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval KPI.
        /// </summary>
        internal static string I_KPI_Approval {
            get {
                return ResourceManager.GetString("I_KPI_Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My PA.
        /// </summary>
        internal static string I_KPI_Employee {
            get {
                return ResourceManager.GetString("I_KPI_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guideline.
        /// </summary>
        internal static string I_KPI_Guideline {
            get {
                return ResourceManager.GetString("I_KPI_Guideline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA Info.
        /// </summary>
        internal static string I_KPI_Info {
            get {
                return ResourceManager.GetString("I_KPI_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Managers.
        /// </summary>
        internal static string I_KPI_Manager {
            get {
                return ResourceManager.GetString("I_KPI_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        internal static string I_KPI_Scheduler {
            get {
                return ResourceManager.GetString("I_KPI_Scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Attachment.
        /// </summary>
        internal static string I_ListAttach {
            get {
                return ResourceManager.GetString("I_ListAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Competency.
        /// </summary>
        internal static string I_ListCompetency {
            get {
                return ResourceManager.GetString("I_ListCompetency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List KPI.
        /// </summary>
        internal static string I_ListKPI {
            get {
                return ResourceManager.GetString("I_ListKPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List News.
        /// </summary>
        internal static string I_ListNews {
            get {
                return ResourceManager.GetString("I_ListNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports &amp; Statistics.
        /// </summary>
        internal static string I_ListPeriod {
            get {
                return ResourceManager.GetString("I_ListPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make News.
        /// </summary>
        internal static string I_MakeNews {
            get {
                return ResourceManager.GetString("I_MakeNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Password.
        /// </summary>
        internal static string I_ManagerPassword {
            get {
                return ResourceManager.GetString("I_ManagerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Record.
        /// </summary>
        internal static string I_Phepton {
            get {
                return ResourceManager.GetString("I_Phepton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay-slip.
        /// </summary>
        internal static string I_PhieuLuong {
            get {
                return ResourceManager.GetString("I_PhieuLuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SW Assessment.
        /// </summary>
        internal static string I_SkillWill {
            get {
                return ResourceManager.GetString("I_SkillWill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Submit Files.
        /// </summary>
        internal static string I_SubmitNews {
            get {
                return ResourceManager.GetString("I_SubmitNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review/ Approval PA.
        /// </summary>
        internal static string liApprovalPA {
            get {
                return ResourceManager.GetString("liApprovalPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeedBacks.
        /// </summary>
        internal static string liFeedBack {
            get {
                return ResourceManager.GetString("liFeedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA History.
        /// </summary>
        internal static string liPA_History {
            get {
                return ResourceManager.GetString("liPA_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Feedbacks.
        /// </summary>
        internal static string liReviewFeedback {
            get {
                return ResourceManager.GetString("liReviewFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seft Assessment.
        /// </summary>
        internal static string liSeftAssessment {
            get {
                return ResourceManager.GetString("liSeftAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set KPI.
        /// </summary>
        internal static string liSetKPI {
            get {
                return ResourceManager.GetString("liSetKPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News management.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager KPI.
        /// </summary>
        internal static string Menu_KPI {
            get {
                return ResourceManager.GetString("Menu_KPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager News.
        /// </summary>
        internal static string Menu_News {
            get {
                return ResourceManager.GetString("Menu_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company News.
        /// </summary>
        internal static string T_News {
            get {
                return ResourceManager.GetString("T_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        internal static string T_NV {
            get {
                return ResourceManager.GetString("T_NV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string T_QL {
            get {
                return ResourceManager.GetString("T_QL", resourceCulture);
            }
        }
    }
}
